services:
    backend:
      image: node:alpine
      volumes:
        - .:/app
      working_dir: /app
      command: npm run dev
      ports:
        - "3008:3000"
        - "3009:9229"
      environment:
        - NODE_ENV=development
        - PORT=3000
        - DATABASE_URL=postgres://postgres:postgres@db/decode
        - MONGO_URL=mongodb://root:password@mongo:27017/decode?authSource=admin
        - JWT_SECRET=myVeryVeryStrongSecret!
      depends_on:
        - db

    db:
      image: postgres:17-alpine
      volumes:
        - db-data:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=decode
    
    mongo:
      image: mongo
      ports:
        - 127.0.0.1:27019:27017
      volumes:
        - mongo-data:/data/db
        - ./SampleCollections:/SampleCollections
      environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=password
      working_dir: /SampleCollections


volumes:
  db-data: {}
  mongo-data: {}
        
      