services:
    backend:
      image: node:alpine
      volumes:
        - .:/app
      working_dir: /app
      command: npm run dev
      ports:
        - "3008:3000"
        - "3009:9229"
      environment:
        - NODE_ENV=development
        - PORT=3000
        - DATABASE_URL=postgres://postgres:postgres@db/decode
        - MONGO_URL=mongodb://mongodb:27017/decode
        - JWT_SECRET=myVeryVeryStrongSecret!
      depends_on:
        - db
        - mongodb

    db:
      image: postgres:17-alpine
      volumes:
        - db-data:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=decode
    
    mongodb:
      image: mongo
      ports:
        - "27019:27017"
      command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
      volumes:
        - mongo-data:/data/db
        - ./SampleCollections:/SampleCollections
      working_dir: /SampleCollections
      healthcheck:
        test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
        interval: 5s
        timeout: 5s
        retries: 5

    mongodb-setup:
      image: mongo:6.0
      container_name: mongodb-setup
      depends_on:
        mongodb:
          condition: service_healthy
      command: >
        mongosh --host mongodb:27017 --eval '
          let count = 0;
          while (count < 10) {
            try {
              let status = rs.status();
              console.log("Replica Set already initialized");
              break;
            } catch (e) {
              console.log("Attempting to initiate Replica Set...");
              try {
                rs.initiate({
                  _id: "rs0",
                  members: [{ _id: 0, host: "localhost:27017" }]
                });
                console.log("Replica Set initiated successfully");
                break;
              } catch (initErr) {
                console.log("Initiate failed, retrying in 2s...", initErr.message);
                sleep(2000);
                count++;
              }
            }
          }
        '


volumes:
  db-data: {}
  mongo-data: {}
        
      